# Generated by Django 5.0.6 on 2024-07-22 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='finMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accountName', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('accountUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transactionId', models.IntegerField()),
                ('transaction', models.CharField(max_length=500)),
                ('accountMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finDataApi.finmeta')),
            ],
        ),
    ]
