# Generated by Django 5.0.6 on 2024-08-18 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finDataApi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeEstimator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income', models.FloatField()),
                ('spending', models.FloatField()),
                ('estimatedBalance', models.FloatField()),
                ('date', models.FloatField()),
                ('accountMeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimator', to='finDataApi.finmeta')),
            ],
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
