# Generated by Django 5.0.6 on 2024-08-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finDataApi', '0002_incomeestimator_delete_transaction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncomeEstimator',
            new_name='BalanceEstimator',
        ),
    ]
