# Generated by Django 5.0.6 on 2024-07-22 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userApi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='accountMeta',
        ),
        migrations.DeleteModel(
            name='finMeta',
        ),
        migrations.DeleteModel(
            name='transaction',
        ),
    ]
