export const ACCESS_TOKEN = "access";
export const REFRESH_TOKEN = "refresh";
export const FIN_ACCESS_TOKEN="access2";
export const FIN_ACCESS_REFRESH ="refresh2";
export const LINK_ID="Link";
export const ACCOUNT_ID="AC-ID";
export const BANK_IMG="img";
export const BALANCE="Int";
export const OWNERNAME="name";
export const GOAL="goal"
